[package]
name = "crates_and_modules"
version = "0.1.0"
edition = "2021"
lisnce = "MIT OR Apache-2.0"
description = "This is test package which has notihing special"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
